config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  devise_for :users
  resources :events do
    resources :tickets
  end
  resource :retirements
end

app/models/event.rb
class Event < ApplicationRecord
  # Association
  belongs_to :owner, class_name: "User"
  has_many :tickets, dependent: :destroy
  has_one_attached :image, dependent: false
  attr_accessor :remove_image

  # Validation
  with_options presence: true do
    validates :name, length: { maximum: 50 }
    validates :place, length: { maximum: 100 }
    validates :content, length: { maximum: 2000 }
    validates :start_at
    validates :end_at
  end

  validate :start_at_should_be_before_end_at

  # scope
  scope :not_started, -> { where("start_at > ?", Time.zone.now) }
  scope :recent, -> { order("start_at")}

  # method
  def created_by?(user)
    return false unless user
    owner_id == user.id
  end

  before_save :remove_image_if_user_accept

  private

  def start_at_should_be_before_end_at
    return unless start_at && end_at

    if start_at >= end_at
      errors.add(:start_at, "は終了時間よりも前に設定してください")
    end
  end

  def remove_image_if_user_accept
    self.image = nil if ActiveRecord::Type::Boolean.new.cast(remove_image)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_event, only: [:edit, :update, :destroy]

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: "「#{@event.name}」を作成しました。"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
    @ticket = current_user.tickets.find_by(event: @event) if current_user
    @tickets = @event.tickets.includes(:user).order(:created_at)
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: "「#{@event.name}」を編集しました。"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy!
    redirect_to root_path, notice: "「#{@event.name}」を削除しました。"
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :content, :start_at, :end_at, :image, :remove_image)
  end

  def set_event
    @event = current_user.created_events.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.haml
- now = Time.zone.now 

%h1.mt-2 イベント情報編集

= form_with( model: @event, class: "form-horizontal", local: true  ) do |f|
  = render partial: "error", locals: { model: @event }
  .form-group.mb-3
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group.mb-3
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group.mb-3
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
  .form-group.mb-3 
    = f.label :end_at
    %div 
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
  .form-group.mb-3 
    = f.label :content
    = f.text_area :content, class: "form-control", row: 10
  .form-group.mb-3
    = f.label :image
    - if @event.image.attached?
      = image_tag(@event.image.variant(resize_to_fit: [400,400]), class: "img-thumbnail d-block mb-3")
    = f.file_field :image, class: "form-control-file"
    - if @event.image.attached?
      .checkbox
        %label
          = f.check_box :remove_image
          画像を削除する
  
  = f.submit class: "btn btn-primary"

app/views/events/new.html.haml
- now = Time.zone.now 

%h1.mt-2 イベント作成

= form_with( model: @event, class: "form-horizontal", local: true ) do |f|
  = render partial: "error", locals: { model: @event }
  .form-group.mb-3
    = f.label :name
    = f.text_field :name, class: "form-control"
  .form-group.mb-3
    = f.label :place
    = f.text_field :place, class: "form-control"
  .form-group.mb-3
    = f.label :start_at
    %div
      = f.datetime_select :start_at, start_year: now.year, end_year: now.year + 1
  .form-group.mb-3 
    = f.label :end_at
    %div 
      = f.datetime_select :end_at, start_year: now.year, end_year: now.year + 1
  .form-group.mb-3 
    = f.label :content
    = f.text_area :content, class: "form-control", row: 10
  .form-group.mb-3
    = f.label :image
    = f.file_field :image, class: "form-control-file"
  
  = f.submit class: "btn btn-primary"

app/views/events/show.html.haml
%h1.mt-3.mb-3= @event.name
.row
  .col-8
    .card.mb-2
      - if @event.image.attached?
        = image_tag @event.image, class: "card-img-top"
    .card.mb-2
      %h5.card-header イベント内容
      .card-body
        %p.card-text= simple_format(h(@event.content), {}, sanitize: false, wrapper_tag: "div")
    .card.mb-2
      %h5.card-header 開催時間
      .card-body
        %p.card-text= "#{l(@event.start_at, format: :long)} - #{l(@event.end_at, format: :long)}"
    .card.mb-2
      %h5.card-header 開催場所
      .card-body
        %p.card-text= @event.place
    .card.mb-2
      %h5.card-header 主催者
      .card-body
        - if @event.owner
          = link_to(url_for_github(@event.owner), class: "card-link") do
            = "@#{@event.owner.nickname}"
        - else
          退会したユーザーです
  .col-4
    - if @event.created_by?(current_user)
      = link_to "イベントを編集する", edit_event_path(@event), class: "btn btn-info btn-lg btn-block mb-3"
      = link_to "イベントを削除する", event_path(@event), data: { turbo_confirm: "「#{@event.name}」を削除します。よろしいですか？", turbo_method: :delete}, class: "btn btn-danger btn-lg btn-block mb-3"
    - if @ticket
      = link_to "参加を取り消す", event_ticket_path(event_id: @event.id, id: @ticket.id), data: { turbo_confirm: "参加を取り消します。よろしいですか？", turbo_method: :delete }, class: "btn btn-warning btn-lg btn-block"
    - elsif user_signed_in?
      %button.btn.btn-primary.btn-lg.btn-block{ "data-bs-toggle": "modal", "data-bs-target": "#createTicket" }
        参加する
      .modal.fade#createTicket
        .modal-dialog
          .modal-content
            .modal-header.d-flex.justify-content-between
              %h4.modal-title#dialogHeader 参加コメント
              %button.close{ type: "button", "data-bs-dismiss": "modal" } &times;
            = form_with(model: @event.tickets.build, url: event_tickets_path(@event)) do |f|
              .modal-body
                = f.text_field :comment, class: "form-control"
              .modal-footer
                %button.btn.btn-default{ type: "button", "data-bs-dismiss": "modal" }
                  キャンセル
                = f.button "送信", class: "btn btn-primary"
    - else
      = link_to "参加する", new_event_ticket_path(@event), class: "btn btn-primary btn-lg btn-block"
    %hr
    .card.mb-2
      %h5.card-header 参加者
      %ul.list-group.list-group-flush
        - @tickets.each do |ticket|
          %li.list-group-item
            - if ticket.user
              = link_to(url_for_github(ticket.user), class: "card-link") do
                = "@#{ticket.user.nickname}"
              = ticket.comment

= link_to "back", :back, class: "link-secondary"