config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  devise_for :users
  resources :events do
    resources :tickets
  end
  resource :retirements
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title AwesomeEvents
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %header.navbar.navbar-expand-sm.navbar-light.bg-light.mb-3
      .container
        = link_to "AwesomeEvents", root_path, class: "navbar-brand"
        %ul.navbar-nav
          - if user_signed_in?
            %li.nav-item
              = link_to current_user.nickname, "#", class: "nav-link"
            %li.nav-item
              = link_to "イベントを作る", new_event_path, class: "nav-link"
            %li.nav-item
              = link_to "ログアウト", destroy_user_session_path, class: "nav-link", data: {turbo_method: :delete}
            %li.nav-item
              = link_to "退会", new_retirements_path, class: "nav-link"
          - else
            %li.nav-item
              = link_to "ログイン", new_user_session_path, class: "nav-link"
            %li.nav-item
              = link_to "新規登録", new_user_registration_path, class: "nav-link"
      -# .container
    - if flash.notice
      .alert.alert-success
        = flash.notice 
    - elsif flash.alert
      .alert.alert-danger
        = flash.alert 
    = yield